"""
models/message.py - Message models for STONE (默行者)

Defines enums and Pydantic models for messages flowing between the
gateway layer and the agent core.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class MessageType(str, Enum):
    """Type classification for incoming messages."""

    TEXT = "text"
    IMAGE = "image"
    FILE = "file"
    AUDIO = "audio"
    COMMAND = "command"      # /slash commands
    SYSTEM = "system"        # Internal system messages


class MessageSource(str, Enum):
    """Origin of the message."""

    FEISHU = "feishu"
    WECHAT = "wechat"
    TELEGRAM = "telegram"
    API = "api"              # Direct REST API call
    INTERNAL = "internal"   # Generated internally by the agent


class UserMessage(BaseModel):
    """A message received from a user via any gateway."""

    message_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    conv_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_id: str = "default_user"
    open_id: str = ""                    # Gateway-specific user identifier

    message_type: MessageType = MessageType.TEXT
    source: MessageSource = MessageSource.API

    content: str = ""
    raw_content: str = ""               # Original unprocessed content from gateway
    attachments: list[str] = Field(default_factory=list)

    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # Routing hints
    task_type: str = "chat"             # chat | code | analysis | search
    privacy_sensitive: bool = False

    model_config = {"arbitrary_types_allowed": True}


class BotResponse(BaseModel):
    """A response generated by the agent to be sent back to the user."""

    response_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    conv_id: str = ""
    user_id: str = "default_user"

    content: str = ""
    source: MessageSource = MessageSource.INTERNAL

    # Dry-run metadata
    requires_confirmation: bool = False
    confirmation_token: str = ""        # conv_id used to look up pending plan

    # Error info
    is_error: bool = False
    error_code: str = ""
    error_message: str = ""

    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # Tool call summary (for audit / display)
    tools_used: list[str] = Field(default_factory=list)

    model_config = {"arbitrary_types_allowed": True}

    @classmethod
    def error_response(
        cls,
        conv_id: str,
        user_id: str,
        error_code: str,
        message: str,
    ) -> "BotResponse":
        return cls(
            conv_id=conv_id,
            user_id=user_id,
            content=f"处理失败：{message}",
            is_error=True,
            error_code=error_code,
            error_message=message,
        )


__all__ = [
    "MessageType",
    "MessageSource",
    "UserMessage",
    "BotResponse",
]
